name: rubhew
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  # flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.1
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.4
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  ios: true
  android: true
  image_path : assets/logo.png
  
flutter_native_splash:
  color: "#00BFFF"  # สีพื้นหลัง (blue)
  image: assets/images/splash_image.png  # ภาพโลโก้
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/iconsgoogle.svg
    - assets/image1.png
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg